namespace Sway.Database.Seeder.Writers;

using Sway.Core.Models;
using Sway.Common;
using System;
using System.Collections.Generic;
using System.Text;
using System.Threading;
using System.Threading.Tasks;

internal class CouponSeedSqlWriter : ISqlWriter<Coupon>
{
    private readonly SqlFileNameBuilder fileNameBuilder;

    public CouponSeedSqlWriter(SqlFileNameBuilder fileNameBuilder)
    {
        this.fileNameBuilder = Guard.ThrowIfNull(fileNameBuilder);
    }

    public Task BulkWriteAsync(IEnumerable<Coupon> entities, CancellationToken cancellationToken)
    {
        var sb = new StringBuilder();

        sb.AppendLine(@"-- ------------------------------------------------------------------------------");
        sb.AppendLine(@"-- <auto-generated>");
        sb.AppendLine(@$"-- This is the seeder file for {nameof(Coupon)}.");
        sb.AppendLine(@$"-- Generated on {DateTime.Now.ToShortDateString()}.");
        sb.AppendLine(@"-- </auto-generated>");
        sb.AppendLine(@"-- ------------------------------------------------------------------------------");
        sb.AppendLine();

        sb.AppendLine(@"USE [Sway];");
        sb.AppendLine();
        sb.AppendLine();

        foreach (var user in entities)
        {
            sb.AppendLine(@$"EXEC {SpNames.AddCouponForUser}");
            sb.AppendLine($"    @UserId = '{user.OwnerId}',");
            sb.AppendLine($"    @Code = '{user.Code}',");
            sb.AppendLine($"    @Description = '{user.Description}',");
            sb.AppendLine($"    @DiscountAmount = {user.DiscountAmount},");
            sb.AppendLine($"    @DiscountUnit = '{user.Type}',");
            sb.AppendLine($"    @ApplicableForBrand = NULL;");

            sb.AppendLine();
        }

        var scriptContent = sb.ToString();

        var fullFilePath = this.fileNameBuilder.Build();

        return File.WriteAllTextAsync(fullFilePath, scriptContent, cancellationToken);
    }
}
