CREATE TABLE [dbo].[Brands] (
    [Id]          UNIQUEIDENTIFIER CONSTRAINT [DF_Brands_Id] DEFAULT NEWID() NOT NULL,
    [Name]        NVARCHAR (50)  CONSTRAINT [UQ_Brands_Name] UNIQUE NOT NULL,
    [Description] NVARCHAR (255) NOT NULL,
    [LogoUrl]     NVARCHAR (255) NULL,
    [CreatedAt]   DATETIME2 (7)  DEFAULT GETDATE() NOT NULL,
    [ModifiedAt]  DATETIME2 (7)  DEFAULT GETDATE() NOT NULL,
    CONSTRAINT [PK_Brands] PRIMARY KEY CLUSTERED ([Id] ASC)
);

