CREATE TABLE [dbo].[Favourites]
(
    [UserId] UNIQUEIDENTIFIER NOT NULL, 
    [ProductId] UNIQUEIDENTIFIER NOT NULL, 
    [IsValid] BIT NOT NULL DEFAULT 1, 
    [CreatedAt] DATETIME2 NOT NULL DEFAULT GETDATE(), 
    [ModifiedAt] DATETIME2 NOT NULL DEFAULT GETDATE(),
    CONSTRAINT [PK_Favourites] PRIMARY KEY CLUSTERED ([UserId] ASC, [ProductId] ASC)
)
