<Project>
  <ItemGroup>
    <PackageVersion Include="Autofac" Version="8.0.0" />
    <PackageVersion Include="Autofac.Configuration" Version="7.0.0" />
    <PackageVersion Include="Bogus" Version="35.6.0" />
    <PackageVersion Include="Dapper" Version="2.1.35" />
    <PackageVersion Include="Microsoft.Extensions.Configuration" Version="10.0.0" />
    <PackageVersion Include="Microsoft.Extensions.Configuration.Json" Version="10.0.0" />
    <PackageVersion Include="Serilog" Version="4.0.0" />
    <PackageVersion Include="SonarAnalyzer.CSharp" Version="9.25.0.90414" />
    <PackageVersion Include="StyleCop.Analyzers" Version="1.2.0-beta.354" />
    <PackageVersion Include="Swashbuckle.AspNetCore" Version="6.4.0" />
    <PackageVersion Include="System.Data.SqlClient" Version="4.8.6" />
  </ItemGroup>
  <!-- Testing packages -->
  <ItemGroup>
    <PackageVersion Include="coverlet.collector" Version="6.0.0" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="17.6.0" />
    <PackageVersion Include="xunit" Version="2.9.2" />
    <PackageVersion Include="xunit.runner.visualstudio" Version="2.8.2" />
  </ItemGroup>
</Project>
